sudo: false
language: ruby
install:
  - git clone https://github.com/ruby/mspec.git ../mspec
script:
  - CHECK_LEAKS=true ../mspec/bin/mspec
matrix:
  include:
    - name: Running each spec twice
      rvm: 2.5.6
      script:
        - CHECK_LEAKS=true ../mspec/bin/mspec -R2 -ff
    - rvm: 2.4.7
    - rvm: 2.5.6
    - rvm: 2.6.4
    - name: RuboCop Lint Checks
      rvm: 2.4.7
      script:
        - gem install rubocop:0.61.0
        - rubocop
branches:
  only:
    - master
    - /^try/
notifications:
  email:
    on_success: change
    on_failure: change
